import { Client } from "pg";
import {
  configuredDatabaseUrl,
  maintenanceDatabaseUrl,
  subjectDatabaseName,
  subjectDatabaseUrl,
} from "./db.js";

const DEMO_DATABASE_NAME = process.env.SUBJECT_DATABASE_NAME?.trim() || "";

/**
 * Provision the small, synthetic customer graph used by the hosted judge path.
 * This is opt-in so normal deployments keep their existing database contract.
 * Render exposes one free Postgres instance, so the bootstrap creates a second
 * database on that instance rather than mixing customer rows with TrueForge's
 * harness tables.
 */
export async function ensureDemoDatabase(): Promise<void> {
  if (process.env.MCP_BOOTSTRAP_DEMO !== "true") return;
  if (!DEMO_DATABASE_NAME) {
    throw new Error("MCP_BOOTSTRAP_DEMO=true requires SUBJECT_DATABASE_NAME");
  }
  if (DEMO_DATABASE_NAME === "postgres") {
    throw new Error("MCP_BOOTSTRAP_DEMO refuses to seed the postgres maintenance database");
  }

  const admin = new Client({ connectionString: maintenanceDatabaseUrl() });
  await admin.connect();
  try {
    const existing = await admin.query<{ datname: string }>(
      "SELECT datname FROM pg_database WHERE datname = $1",
      [DEMO_DATABASE_NAME],
    );
    if (existing.rowCount === 0) {
      const safeName = `\"${DEMO_DATABASE_NAME.replaceAll('"', '""')}\"`;
      await admin.query(`CREATE DATABASE ${safeName}`);
    }
  } finally {
    await admin.end();
  }

  // Keep this check close to the connection code: it catches a malformed
  // Render URL before the service starts accepting MCP sessions.
  new URL(configuredDatabaseUrl());
  const db = new Client({ connectionString: subjectDatabaseUrl() });
  await db.connect();
  try {
    await db.query(`
      CREATE TABLE IF NOT EXISTS customers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL,
        full_name TEXT NOT NULL,
        phone TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS addresses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        line1 TEXT NOT NULL,
        city TEXT NOT NULL,
        postcode TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS uploads (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        filename TEXT NOT NULL,
        object_key TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS support_tickets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
        subject TEXT NOT NULL,
        body TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS audit_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
        action TEXT NOT NULL,
        at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        total_cents INTEGER NOT NULL,
        placed_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS order_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        sku TEXT NOT NULL,
        qty INTEGER NOT NULL,
        unit_price_cents INTEGER NOT NULL
      );
      CREATE TABLE IF NOT EXISTS retention_policies (
        table_name TEXT PRIMARY KEY,
        basis TEXT NOT NULL,
        retain_years INTEGER NOT NULL,
        pii_columns TEXT[] NOT NULL,
        anonymise_columns TEXT[] NOT NULL
      );
      CREATE INDEX IF NOT EXISTS addresses_customer_id_idx ON addresses(customer_id);
      CREATE INDEX IF NOT EXISTS uploads_customer_id_idx ON uploads(customer_id);
      CREATE INDEX IF NOT EXISTS support_tickets_customer_id_idx ON support_tickets(customer_id);
      CREATE INDEX IF NOT EXISTS audit_log_customer_id_idx ON audit_log(actor_customer_id);
      CREATE INDEX IF NOT EXISTS orders_customer_id_idx ON orders(customer_id);
      CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items(order_id);
    `);

    await db.query(`
      INSERT INTO customers (id, email, full_name, phone)
      SELECT id, 'customer-' || id || '@example.invalid', 'Customer ' || id,
             '+1-555-' || lpad(id::text, 4, '0')
        FROM generate_series(1, 4500) AS ids(id)
       WHERE id <> 4471
      ON CONFLICT (id) DO NOTHING;
      INSERT INTO customers (id, email, full_name, phone, created_at)
      VALUES (4471, 'cleo.testsubject@example.invalid', 'Cleo Testsubject', '+1-555-4471', '2022-01-11T11:15:00Z')
      ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, full_name = EXCLUDED.full_name, phone = EXCLUDED.phone;

      INSERT INTO addresses (id, customer_id, line1, city, postcode)
      VALUES
        (4471001, 4471, '1 Imaginary Way', 'Springfield', 'ZZ1 1ZZ'),
        (4471002, 4471, '2 Imaginary Way', 'Springfield', 'ZZ2 2ZZ'),
        (4471003, 4471, '3 Imaginary Way', 'Springfield', 'ZZ3 3ZZ')
      ON CONFLICT (id) DO NOTHING;
      INSERT INTO uploads (id, customer_id, filename, object_key)
      VALUES
        (4471001, 4471, 'customer-4471-document-1.pdf', 'synthetic/4471/document-1.pdf'),
        (4471002, 4471, 'customer-4471-document-2.pdf', 'synthetic/4471/document-2.pdf')
      ON CONFLICT (id) DO NOTHING;
      INSERT INTO support_tickets (id, customer_id, subject, body)
      VALUES (4471001, 4471, 'Where is my synthetic order?', 'Generated support ticket for the subject-data test.')
      ON CONFLICT (id) DO NOTHING;
      INSERT INTO audit_log (id, actor_customer_id, action, at)
      VALUES
        (4471001, 4471, 'account_created', '2025-01-04T10:00:00Z'),
        (4471002, 4471, 'login', '2025-02-14T12:00:00Z'),
        (4471003, 4471, 'profile_updated', '2025-03-18T09:00:00Z'),
        (4471004, 4471, 'checkout_completed', '2025-04-22T16:00:00Z')
      ON CONFLICT (id) DO NOTHING;

      INSERT INTO orders (id, customer_id, total_cents, placed_at)
      SELECT 4471000 + n, 4471, 5000 + (n * 725), '2025-05-01T12:00:00Z'::timestamptz + (n * interval '1 day')
        FROM generate_series(1, 8) AS rows(n)
      ON CONFLICT (id) DO NOTHING;
      INSERT INTO order_items (id, order_id, sku, qty, unit_price_cents)
      SELECT 447100000 + ((order_index - 1) * 5) + item_index,
             4471000 + order_index,
             'SKU-4471-' || order_index || '-' || item_index,
             1 + (item_index % 3), 500 + (item_index * 250)
        FROM generate_series(1, 8) AS orders(order_index)
        CROSS JOIN generate_series(1, 5) AS items(item_index)
      ON CONFLICT (id) DO NOTHING;

      INSERT INTO retention_policies (table_name, basis, retain_years, pii_columns, anonymise_columns)
      VALUES
        ('orders', 'tax', 7, '{}', '{}'),
        ('order_items', 'tax', 7, '{}', '{}'),
        ('customers', 'none', 0, '{email,full_name,phone}', '{email,full_name,phone}'),
        ('support_tickets', 'none', 0, '{subject,body}', '{}')
      ON CONFLICT (table_name) DO UPDATE SET
        basis = EXCLUDED.basis,
        retain_years = EXCLUDED.retain_years,
        pii_columns = EXCLUDED.pii_columns,
        anonymise_columns = EXCLUDED.anonymise_columns;
    `);
  } finally {
    await db.end();
  }

  console.log(`[bootstrap] subject database ${DEMO_DATABASE_NAME} is ready with synthetic customer data`);
}
