BEGIN;

CREATE TABLE customers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      TEXT NOT NULL,
  full_name  TEXT NOT NULL,
  phone      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE addresses (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  line1       TEXT NOT NULL,
  city        TEXT NOT NULL,
  postcode    TEXT NOT NULL
);

CREATE TABLE uploads (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  filename    TEXT NOT NULL,
  object_key  TEXT NOT NULL
);

CREATE TABLE support_tickets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  subject     TEXT NOT NULL,
  body        TEXT NOT NULL
);

CREATE TABLE audit_log (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  action            TEXT NOT NULL,
  at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE orders (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  total_cents INTEGER NOT NULL,
  placed_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  sku              TEXT NOT NULL,
  qty              INTEGER NOT NULL,
  unit_price_cents INTEGER NOT NULL
);

CREATE TABLE retention_policies (
  table_name        TEXT PRIMARY KEY,
  basis             TEXT NOT NULL,
  retain_years      INTEGER NOT NULL,
  pii_columns       TEXT[] NOT NULL,
  anonymise_columns TEXT[] NOT NULL
);

INSERT INTO retention_policies
  (table_name, basis, retain_years, pii_columns, anonymise_columns)
VALUES
  ('orders',          'tax',  7, '{}',                      '{}'),
  ('order_items',     'tax',  7, '{}',                      '{}'),
  ('customers',       'none', 0, '{email,full_name,phone}', '{email,full_name,phone}'),
  ('support_tickets', 'none', 0, '{subject,body}',           '{}');

COMMIT;
